# Site settings
title: A personal portfolio about software
description: A personal portfolio about design, development software systems
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://laoth.github.io/portfolio/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gustavo Sánchez
user_description: Software Architect
user_title: Software Architect
email: laotshi@gmail.com
twitter_username: laotshi
github_username:  Laoth
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
